# install.packages(data.table)
# install.packages(matrixStats)
# install.packages(stats)
# install.packages(gplots)
# install.packages(DESeq2)
# install.packages(ggplot2)
# install.packages(RColorBrewer)
# install.packages(pheatmap)
# 
# library(data.table)
# library(matrixStats)
# library(stats)
# library(gplots)
# library(DESeq2)
# library(ggplot2)
# library(RColorBrewer)
# library(pheatmap)

cs15_forelimb <- read.table("/home/stellab/private/genome_analysis/results/7_differential_expression/htseq_count.txt")
cs15_hindlimb <- read.table("/home/stellab/private/genome_analysis/results/7_differential_expression/htseq_count.txt")
cs16_forelimb <- read.table("/home/stellab/private/genome_analysis/results/7_differential_expression/htseq_count.txt")
cs16_hindlimb <- read.table("/home/stellab/private/genome_analysis/results/7_differential_expression/htseq_count.txt")

print(cs15_forelimb)
